version: '3.8'

services:
  chatbot:
    build: .
    container_name: streamlit_container
    ports:
      - "8501:8501"
    environment:
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - GOOGLE_APPLICATION_CREDENTIALS=/tmp/keys/FILE_NAME.json
    volumes:
      - app_volume:/home/app/data
      # - ~/.config/gcloud/application_default_credentials.json:/tmp/keys/FILE_NAME.json:ro # for local container
      - /home/streamlitadmin/tolkai_project/credentials.json:/tmp/keys/FILE_NAME.json:ro
    env_file:
      - ./.env
    restart: always

volumes:
  app_volume: