# This set of tasks is for installing and running docker. 
# The user streamlitadmin is added to the docker group and has permission to run docker without sudo.
---
- hosts: streamlit_cluster
  become: true
  tasks:
    - name: install dependencies
      apt:
        name: "{{item}}"
        state: present
        update_cache: yes
      loop:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg-agent
        - software-properties-common

    - name: Get the GPG Key
      apt_key:
        url: https://download.docker.com/linux/debian/gpg
        state: present


    - name: Add docker Repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable
        state: present

    - name: Install Docker
      apt:
        name: "{{item}}"
        state: latest
        update_cache: yes
      loop:
        - docker-ce
        - docker-ce-cli
        - containerd.io
    # sudo groupadd docker
    - name: Create "docker" group
      group:
        name: "docker"
        state: present

    # sudo usermod -aG docker root
    - name: Add remote "debian" user to "docker" group
      user:
        name: "streamlitadmin"
        groups: 
          - "docker"
        append: yes
    - name: Start the docker service
      service:
        name: docker
        state: started
        enabled: yes
  handlers:
    - name: restart docker
      service: 
        name: docker 
        state: restarted
