- hosts: streamlit_cluster
  become: true
  vars:
    streamlit_volume: "/home/app/data"
    remote_project_path: "/home/streamlitadmin/tolkai_project"

  tasks:
    - name: Check for existing Streamlit container
      command: docker ps -a -q -f name=streamlit_container
      register: streamlit_container
      failed_when: streamlit_container.rc != 0

    - name: Stop existing Streamlit container
      command: docker stop streamlit_container
      when: streamlit_container.stdout != ""

    - name: Remove existing Streamlit container
      command: docker rm streamlit_container
      when: streamlit_container.stdout != ""

    - name: Check if port 8501 is in use
      shell: netstat -tuln | grep -E ':8501'
      register: port_check
      failed_when: port_check.rc == 0
      ignore_errors: true

    - name: Fail if port 8501 is in use by another process
      fail:
        msg: "Port 8501 is already in use by another process"
      when: port_check.rc == 0 and streamlit_container.stdout == ""

    - name: Ensure the Git project directory is absent
      file:
        path: "{{ remote_project_path }}"
        state: absent
      become: true

    - name: Ensure correct ownership and permissions for the project directory
      file:
        path: "/tolkai_project"
        state: directory
        owner: streamlitadmin
        group: streamlitadmin
        mode: '0755'
      become: true

    - name: Clone the Git repository
      git:
        repo: 'https://github.com/el-tegy/TolkAI.git'
        dest: "{{ remote_project_path }}"
        version: 'feature/v1.1.0-containerization'
        clone: yes
        update: yes
      become_user: streamlitadmin
    
    - name: Copy .env file to project directory
      template:
        src: /home/samuel/Bureau/Github/TolkAI/.env
        dest: "/home/streamlitadmin/tolkai_project/.env"

    - name: Change ownership of the .env file
      file:
        path: "/home/streamlitadmin/tolkai_project/.env"
        owner: streamlitadmin
        group: streamlitadmin
      become: true
    
    # - name: Check if .env file exists
    #   command: ls -la /home/streamlitadmin/tolkai_project/
    #   register: ls_output

    # - name: Show ls output
    #   debug:
    #     var: ls_output.stdout_lines

    - name: Start Streamlit with Docker Compose
      shell: >
        cd {{ remote_project_path }} && docker compose up -d
      when: port_check.rc != 0 or streamlit_container.stdout != ""
    
    - name: Restart Streamlit Docker Container
      command: docker restart streamlit_container
      become: true

  handlers:
    - name: restart docker
      service:
        name: docker
        state: restarted
